from django.db import models

# Create your models here.

class cars(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    brand = models.TextField()
    model = models.TextField()
    price = models.IntegerField()

class NewCars(models.Model):
    created =models.DateTimeField(auto_now_add=True)
    added = models.DateTimeField(default='')
    brand = models.CharField(max_length=100, default='')
    model = models.CharField(max_length=100, default='')
    price = models.IntegerField(default=0)
    year = models.IntegerField(default=0)
    displacment = models.IntegerField(default=0)
    fuel = models.CharField(max_length=100, default='')
    power = models.IntegerField(default=0)
    gearbox = models.CharField(max_length=100, default='')
    milage = models.IntegerField(default=0)
    drive = models.CharField(max_length=100, default='')
    chassis = models.CharField(max_length=100, default='')
    color = models.CharField(max_length=100, default='')
    import_country = models.CharField(max_length=100, default='')

class DailyAvg(models.Model):
    date = models.DateTimeField(default='')
    price = models.IntegerField(default=0)
    count = models.IntegerField(default=0)
    class Meta:
       ordering = ('date',)

class DailyPlots(models.Model):
    _Petrol = models.IntegerField(default=0)
    _Diesel = models.IntegerField(default=0)
    _Hybrid = models.IntegerField(default=0)
    _Electric = models.IntegerField(default=0)

    _10 = models.IntegerField(default=0)
    _20 = models.IntegerField(default=0)
    _30 = models.IntegerField(default=0)
    _40 = models.IntegerField(default=0)
    _50 = models.IntegerField(default=0)
    _60 = models.IntegerField(default=0)
    _70 = models.IntegerField(default=0)
    _80 = models.IntegerField(default=0)
    _90 = models.IntegerField(default=0)
    _100 = models.IntegerField(default=0)
    _110 = models.IntegerField(default=0)
    _120 = models.IntegerField(default=0)
    _130 = models.IntegerField(default=0)
    _140 = models.IntegerField(default=0)
    _150 = models.IntegerField(default=0)
    _160 = models.IntegerField(default=0)
    _170 = models.IntegerField(default=0)
    _180 = models.IntegerField(default=0)
    _190 = models.IntegerField(default=0)
    _200 = models.IntegerField(default=0)
    _210 = models.IntegerField(default=0)
    _220 = models.IntegerField(default=0)
    _230 = models.IntegerField(default=0)
    _240 = models.IntegerField(default=0)
    _250 = models.IntegerField(default=0)
    _260 = models.IntegerField(default=0)
    _270 = models.IntegerField(default=0)
    _280 = models.IntegerField(default=0)
    _290 = models.IntegerField(default=0)
    _300 = models.IntegerField(default=0)

    _Black = models.IntegerField(default=0)
    _Red = models.IntegerField(default=0)
    _Gray = models.IntegerField(default=0)
    _Blue = models.IntegerField(default=0)
    _Silver = models.IntegerField(default=0)
    _White = models.IntegerField(default=0)
    _Other = models.IntegerField(default=0)
