# Generated by Django 4.1 on 2022-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added', models.DateTimeField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('displacment', models.IntegerField()),
                ('fuel', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('gearbox', models.CharField(max_length=100)),
                ('drive', models.CharField(max_length=100)),
                ('chassis', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('import_country', models.CharField(max_length=100)),
            ],
        ),
    ]
